### ISSUE TITLE
Installation through NPM currently failing

### ISSUE THREAD

**Issue by ghost** [pkuleon/javascript-to-lua#2]
Exactly as for https://github.com/npm/newww/issues/984 - So, may not be fixable at your end, or may be a Travis issue like OP over there?

I installed using the git URL, but it didn't install the `js-to-lua` script alongside the lib, so I'm having to call it explicitly using `node /usr/lib/node_modules/js-to-lua/colony.js`.

**Comment by akavel** [comment]
I'm having a similar problem; also when running `node .../node_modules/js-to-lua/colony.js my_app.js`, I'm seeing an error message like below:
```
Syntax error on "my_app.js"
 Type error: node.update.source is not a function
    at colonize (.../node_modules/js-to-lua/colony.js:333:35)
    at walk (.../node_modules/falafel/index.js:60:9)
    ...
```
